export default {
  computed: {
    appData () {
      return {
        title: 'HAPPY BDAY TIA DESSA :)',
        socialLinks: [
          { name: 'Facebook', icon: 'mdi-facebook', link: 'https://facebook.com', color: '#0F98F6' },
          { name: 'Instagram', icon: 'mdi-instagram', link: 'https://instagram.com', color: '#EF0075' },
          { name: 'Twitter', icon: 'mdi-twitter', link: 'https://twitter.com', color: '#1A91DA' },
          { name: 'Soundcloud', icon: 'mdi-soundcloud', link: 'https://soundcloud.com', color: '#FF5501' },
          { name: 'Twitch', icon: 'mdi-twitch', link: 'https://twitch.tv', color: '#9147FF' },
          { name: 'Youtube', icon: 'mdi-youtube', link: 'https://youtube.com', color: '#FE0200' },
          { name: 'LinkedIn', icon: 'mdi-linkedin', link: 'https://linkedin.com', color: '#0077B5' },
        ],
        contact: {
          phone: { value: '+1 555 555-5555', icon: 'mdi-phone' },
          email: { value: 'sample@example.com', icon: 'mdi-email' },
        },
        recentNews: [
          'Lorem ipsum dolor sit amet, consectetur.',
          'Donec at nunc eget massa bibendum ultrices.',
          'Donec non sem fermentum, malesuada augue.',
          'Sed pharetra metus vitae diam blandit.',
          'Proin quis lacus lobortis, semper arcu.',
        ],
        blogPosts: [
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date().toLocaleDateString(),
            to: { name: 'Home' },
          },
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24).toLocaleDateString(),
            to: { name: 'Home' },
          },
          {
            title: 'Lorem ipsum dolor sit amet',
            text: 'Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima. Ut enim ad minima veniam, quis nostrum exercitatio ut enim ad minima.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toLocaleDateString(),
            to: { name: 'Home' },
          },
        ],
        recentPosts: [
          {
            text: 'Lorem ipsum dolor sit amet, consectetur. Donec at nunc eget massa bibendum ultrices.',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
          },
          {
            text: 'Donec non sem fermentum, malesuada augue. Sed pharetra metus vitae diam blandit.',
            date: new Date(Date.now() - 1000 * 60 * 60 * 24).toLocaleDateString('en-US', { month: 'long', day: 'numeric' }),
          },
        ],
        projects: [
          {
            id: 7,
            src: require('@/assets/projects/7.jpeg'),
            title: 'Tony',
            subtitle: 'Te amo muito!!!',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'A pessoa mais importante pra mim. .....',
            tags: ['tony', 'amor'],
            category: 'family',
          },
          {
            id: 9,
            src: require('@/assets/projects/9.jpeg'),
            title: 'Sofia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst. Donec scelerisque ante ante, vel tempor dolor auctor ut. Sed et luctus leo, eu egestas sapien. In semper commodo urna, id lacinia mi pretium eu. Suspendisse ornare blandit ligula id fermentum. Nulla lobortis, ligula quis consequat elementum, elit odio fringilla ligula, commodo tristique leo elit ac ex. Vestibulum semper sagittis odio sed aliquam. Pellentesque at turpis vel augue scelerisque malesuada at sit amet augue.',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 12,
            src: require('@/assets/projects/15.jpg'),
            title: 'Carol, Rogerio e Rafael',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Denguinho! Feliz aniversário!!!Difícil escrever resumido tão grandes coisas para falar de você! Obrigada por ser tão querida, especial, amiga que você é. Te desejamos tudo de mais maravilhoso que você merece: saúde, muitas felicidades, paz, realizações e muitos anos de vida! Daremos o abraço pessoalmente! Com carinho, Carol Rogério e Rafael.',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 13,
            src: require('@/assets/projects/16.jpg'),
            title: 'Renata, Guilherme, Vitor e Joao',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa , somos uma família cheia de sorte  . Ganhamos  uma amiga, companheira , pessoa maravilhosa que alegra nossos encontros . Além de tudo ainda perde todas as partidas de buraco 😂. Você é muito especial, desejamos muita saúde , felicidades e bençãos . Que possamos comemorar muitos anos juntos !! Re, Gui, Victor e João.',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 14,
            src: require('@/assets/projects/18.jpg'),
            title: 'Babi e Andre',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Denguinho, que nesta data especial você tenha um dia cheio de alegrias! Que Deus te Ilumine sempre e que nunca te faltem razões para brindar muito essa vida boa!! Feliz aniversário e tudo de bom!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 15,
            src: require('@/assets/projects/19.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Loirao, parabéns! Quero agradecer por ser tão especial na minha vida. Você mora no meu coração e a sua amizade significa muito para mim.Você merece tudo de melhor que a vida pode oferecer. Felicidades sempre! Te amamos!!!!!',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 16,
            src: require('@/assets/projects/25.jpg'),
            title: 'Jenny, Beto, Baby Bobby e Vivi',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Feliz aniversário, Denguinho!  Muita saúde, paz, calma, amor e tudo mais.  Nos 4 te amamos muito! Jenny, Beto, Bobby e Vivi',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 17,
            src: require('@/assets/projects/26.jpg'),
            title: 'Cynthia, Betinho, Fernanda, Sofia, Julia e Leao',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Oi Denguinha, que Deus te de muita saude, paz, e sua familia maravilhosa. Meus parabens e obrigada por ser esta pessoa tao especial em nossas vidas. ',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 18,
            src: require('@/assets/projects/31.jpg'),
            title: 'Pri, Mike, Julie, Bella e Leo',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Denguinho,  Feliz aniversário para uma das pessoas mais especiais e forte que eh conheço! Tenha um ano tão incrível quanto o seu coração! Desejamos pro vice o melhor que a vida tem para oferecer! Te amamos!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 19,
            src: require('@/assets/projects/32.jpg'),
            title: 'Leozinho',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Para minha tia tão linda, obrigada por sempre estar presente e todos os mimos comigo',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 20,
            src: require('@/assets/projects/33.jpg'),
            title: 'Angelina, Bella, Alice e Julie',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Obrigada tia dessa por sempre nos receber de braços abertos na sua casa',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 21,
            src: require('@/assets/projects/34.jpg'),
            title: 'Bella',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Didi, I love you so much, da Bellinha',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 22,
            src: require('@/assets/projects/36.jpg'),
            title: 'Julie',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Tia dessa, eu te amo!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 23,
            src: require('@/assets/projects/37.jpg'),
            title: 'Caseys Family',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'We love you! Muita saude pra gente poder viajar muito nessa vida juntos!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 24,
            src: require('@/assets/projects/38.jpg'),
            title: 'Tia Le',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa querida, que  Deus te abençoe neste novo ciclo, traga oportunidades incríveis, crescimento, desejos sinceros, abraços carinhosos e Muitas Felicidades. Feliz aniversário! Bjuss da tia Lê.',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 25,
            src: require('@/assets/projects/41.jpg'),
            title: 'Michelle, Michel, Alice e Ian',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Feliz aniversário querida amiga!! Para vc desejamos muita luz, alegria e saúde! Que felicidade a nossa ter uma pessoal tão especial como vc em nossas vidas. Amamos vc!! Amo vc, minha amiga irmã que ganhei aqui nos States! Michel, Michelle, Alice e Ian',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 26,
            src: require('@/assets/projects/42.jpg'),
            title: 'Tia Vera',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa tenha um feliz aniversário cheio de sorrisos e gargalhadas, repleto de paz, amor e muita alegria. Parabéns por mais um ano de vida! Beijos da tia que te ama muito. Tia Vera',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 27,
            src: require('@/assets/projects/43.jpg'),
            title: 'Iara',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Parabéns minha filha, te desejo sempre muita saúde, junto aos teus filhos e o tony, que a vida te dê todas bençãos que mereces. Te amo muito!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 28,
            src: require('@/assets/projects/44.jpg'),
            title: 'Iara',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Te amo!',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 29,
            src: require('@/assets/projects/45.jpg'),
            title: 'Katia, Thiago e Mateus',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa vc e um ser humano maravilhoso, uma mulher deslumbrante e uma amiga mais que especial. Tem um lugar garantido em meu coração! Te amamos!',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 30,
            src: require('@/assets/projects/48.jpg'),
            title: 'Marcella, Guilherme, Gabriela e Julia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Menina doce como um mel e feroz como uma leoa, Voce conquista com seu dom de servir e se doar,  e atrai com esse jeito protetora e ousada. Vc é amiga, amiga mesmo, e essa é a sua maior qualidade. Vc traz um calor humano sem igual e uma energia que contagia. Eu acredito que cada pessoa vem ao mundo com qualidades que precisamos pra fazer o mundo melhor,  e eu não tenho dúvida que voce veio para ensinar como amar o próximo. Vc é um presente pra cada pessoa que tem o previlégio de fazer parte da sua vida. Obrigada por vc existir e trazer tanta coisa boa de graça assim. Marcella, Gui, Gabi e Julia',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 31,
            src: require('@/assets/projects/50.jpg'),
            title: 'Tio Ademir, Tia Karla e Matheus',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Essa foto representa o carinho que temos por você Andressa. Feliz aniversário! Que esse novo ciclo seja de muita luz , paz , alegria, saúde e realizações. Continue levando essa alegria e esse sorriso que por onde passa contagia as pessoas e deixa tudo mais leve. Um grande beijo do teu padrinho e tio Ademir, da tia Karla e do Matheus. ',
            tags: ['tag', 'tag', 'tag'],
            category: 'family',
          },
          {
            id: 32,
            src: require('@/assets/projects/52.jpg'),
            title: 'Ana Pati, Roger, Nicholas e Natalie',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Dressinhaaaa, Te desejo tudo de melhor neste novo ciclo. Você nunca mede esforços para ajudar o próximo, sempre está disponível e pronta para ajudar a todos, que briga comigo mas logo abre um sorrisão 😁, sempre anima os encontros e tem a casa sempre aberta para nos receber 💛. Obrigada pela nossa amizade, por rir das minhas piadas bestas, e por nunca ter compartilhado teu chimarrão comigo! 🤣 Sabe que sou meia louca mas te amo! 💛 Um beijo grande! Parabéns!!! 😘😘😘 Ana Pati, Roger, Nicholas & Natalie',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 33,
            src: require('@/assets/projects/54.jpg'),
            title: 'Tia Suzete e familia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Parabéns minha afilhada,muita saúde,paz, amor, prosperidade e muitos sonhos à realizar;que Deus esteja sempre te iluminando! Te amo, te amo e aproveita teu dia! Tia e madrinha Suzete e família.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 34,
            src: require('@/assets/projects/55.jpg'),
            title: 'Vó Celmira',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa, hoje é teu dia, o aniversario, muita saúde, felicidades e luz. Que Deus te abençoe sempre, com essa alegria, força e sucesso, na vida em família. Abraço, saudades de tua vó Celmira!',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 35,
            src: require('@/assets/projects/56.jpg'),
            title: 'Tia Tereza',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa desde que nasceu és luz , ilumina a família toda . Obrigada por ser esta pessoa tão especial , feliz aniversário . Ti amo !!!! Tia Tereza bjsss',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 36,
            src: require('@/assets/projects/57.jpg'),
            title: 'Prima Elise',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa Querida que este sorriso lindo sempre faça presente nos teus dias, que continue a alegrar à todos que te cercam. Desejamos que este novo ciclo seja repleto de amor, bençãos e saúde. Que as surpresas da vida sejam como a desse dia!!! Feliz aniversário!!! Te amamos❤️',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 37,
            src: require('@/assets/projects/58.jpg'),
            title: 'Tia Ivette',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa!!! Feliz aniversário!! Que esse e todos os outros anos da sua vida sejam maravilhosos,  repletos de muitas realizações, saúde,  paz e alegrias,  junto aos teus. Estamos com muitas saudades. Te amo minha querida 😍😍',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 38,
            src: require('@/assets/projects/59.jpg'),
            title: 'Pai',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa, parabéns pelo teu aniversário, tenho muito orgulho de você e também de meus netos; gostaria de estar presente nesta comemoração,mas não é possível,não faltará oportunidade,quando vieres ao Brasil, venha visitar me, aí faremos uma festa e comemoramos juntos. Aproveite esta comemoração e seja muito feliz! Beijos do teu pai',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 39,
            src: require('@/assets/projects/60.jpg'),
            title: 'Anna, Daniel, Sophie e Cecilia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Parabéns minha querida!!! Que Deus abençoe essa nova volta em torno do Sol! Tudo de melhor nessa vida. Obrigada por sempre me receber tão bem nesse “mundo novo”, desde o início. Que seu dia seja leve e cheio de diversão! Dessa vez não poderei estar presente então… Bebe uma por mim! Ps: Precisamos renovar essa foto🥰',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 40,
            src: require('@/assets/projects/61.jpg'),
            title: 'Sofia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Tia Dessa! Hoje é um dia especial na vida de todos nos, que temos a sorte de ter voce nas nossas vidas. Uma moça do coracao enorme, uma  bondade de outro mundo, muito amiga, companheira, fiel. Uma pessoa que está ali estendendo a mao pro que for e a hora que for. Sempre. Voce chegou na nossa familia e nos trouxe muita alegria. Obrigada por ser esta pessoa incrivel. Te desejo muuita saude, paz, felicidade e muita musica brasileira que a gente adora! Que Deus continue abencoando o caminho de voce e da sua familia. Sou muito grata por ter voces na minha vida. Obrigada por tudo! Te amamos demais! E estamos com voce sempre! Beijo no coracao, Tia Soca.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 41,
            src: require('@/assets/projects/62.jpg'),
            title: 'Dani',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Bonita! O que falar pra você nesse dia? Peço a Deus que continue te preservando assim, Feliz, Alegre, sempre com um coração disposto a ajudar que não mede esforço , que você possa continuar colhendo os melhores frutos dessa vida pois você merece muito! Parabéns, adoro você!❤️',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 42,
            src: require('@/assets/projects/17.jpg'),
            title: '',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 43,
            src: require('@/assets/projects/20.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Amamos voce!',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 44,
            src: require('@/assets/projects/21.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Minha loirao',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 45,
            src: require('@/assets/projects/22.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 46,
            src: require('@/assets/projects/23.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 47,
            src: require('@/assets/projects/24.jpg'),
            title: 'Fe, Christian, Gabizinho e Angelina',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 49,
            src: require('@/assets/projects/29.jpg'),
            title: 'Tia Cynthia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Parabens Denguinha! Que seu novo ciclo seja repleto de muito amor, saude, realizacoes. Te amamos!! Aproveita muito a festanca',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 50,
            src: require('@/assets/projects/35.jpg'),
            title: 'Bellinha',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Te amo tia Dessa',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 51,
            src: require('@/assets/projects/39.jpg'),
            title: 'Michelle',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Amiga especial!',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 52,
            src: require('@/assets/projects/46.jpg'),
            title: 'Katia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Amiga especial!',
            tags: ['tag', 'tag', 'tag'],
            category: 'friends',
          },
          {
            id: 53,
            src: require('@/assets/projects/47.jpg'),
            title: 'Katia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Amiga especial!',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 54,
            src: require('@/assets/projects/49.jpg'),
            title: 'Marcella',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Amiga especial!',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 55,
            src: require('@/assets/projects/51.jpg'),
            title: 'Ana Pati, Roger, Nicholas e Natalie',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 56,
            src: require('@/assets/projects/53.jpg'),
            title: '',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 57,
            src: require('@/assets/projects/63.jpg'),
            title: 'Tia Soca e Tia Dessa',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Te amo Tia Dessa',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 58,
            src: require('@/assets/projects/64.jpg'),
            title: '',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: '',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 59,
            src: require('@/assets/projects/66.jpg'),
            title: 'Tia Dessa, Tio Tony e Tia Soca',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Obrigada por tudo! Voce e pedra preciosa.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 60,
            src: require('@/assets/projects/67.jpg'),
            title: 'Claudia, Eduardo e Davi',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Parabéns amadaaa!! Como amo celebrar a sua vida! Você é uma mulher guerreira e de muitas qualidades, mas acima de tudo és uma amiga especial com quem podemos contar para tudo e sempre. Muitas felicidades, porque você merece!!! Que Deus continue iluminando seus dias com muito amor e paz, e que abençoe seu caminho com saúde, sucesso e alegrias sem fim! Claudia e familia.',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 61,
            src: require('@/assets/projects/68.jpg'),
            title: 'Marcela e Henrique',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Feliz aniversário Denguinho! Você é luz, vem e aquece. Abre gargalhadas no tempo, espaço, irradia alegria, e coloca todos pra dançar. Não deixa ninguém esmorecer, da de si o olhar atento. Você é carinho, conforto, amor. Você merece o mundo. Feliz aniversário amiga querida!! Muitos anos de vida cheios de saúde, bençãos e motivos pra comemorar! ✨✨',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 62,
            src: require('@/assets/projects/69.jpg'),
            title: 'Dani',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Como ser tão gata, engraçada, fortaleza, ninho! Pois é! Tu és uma combinação peculiar entre inspirações e suspiros. Que onde chega colore o ambiente e traz alegria a todos que estão a tua volta. Que siga abençoada de saúde e energia, vitalidade e aprendizados. Que todos os teus sonhos se realizem. Que a vida continue te mostrando o quanto ela pode ser pode boa de se viver! Te amo hoje e sempre! Feliz vida! 🌈✨🎁❤️🎈',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 63,
            src: require('@/assets/projects/70.jpg'),
            title: 'Jana',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Te amo!',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 64,
            src: require('@/assets/projects/71.jpg'),
            title: 'Sandra, Antonio e familia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Andressa Querida♥️🎉🥳🥳Que o Amor continue sendo derramado em voce e a partir de você ♥️Te admiramos muito e te desejamos um caminho de Com muita Saúde Paz e Alegrias 🙌♥️🎉🎉🥳🥳🥳Parabéns !!🎉🎉🥳Feliz Aniversário 🎂 com muito carinho de seus amigos Sandra e Antônio !!♥️Beijo grande 😘🎉🎉🥳🥳🥳🥳',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
          {
            id: 65,
            src: require('@/assets/projects/72.jpg'),
            title: 'Tuca e familia',
            subtitle: 'Unsplash',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            description: 'Tia Dêssa, continue sendo essa pessoa maravilhosa que você é. Ser humano de coração generoso, esposa dedicada, mãe  cuidadosa, amiga leal, mulherão da pohah... Tá, eu sei que é um pouco nervosa... Mas e daí? Seu nervoso é só fogo de palha, logo passa..🤣 Saiba que vc é muito amada e um privilégio quem te tem por perto. Bjs 😘',
            tags: ['tag', 'tag', 'tag'],
            category: 'night',
          },
        ],
        instagramPosts: [
          {
            id: 1,
            src: require('@/assets/instagram/ahmad-kadhim-GeHVEDrqMB8-unsplash.jpg'),
          },
          {
            id: 2,
            src: require('@/assets/instagram/ciocan-ciprian-XGny9I-k9RM-unsplash.jpg'),
          },
          {
            id: 3,
            src: require('@/assets/instagram/lukasz-szmigiel-dAgtO5H8cXg-unsplash.jpg'),
          },
          {
            id: 4,
            src: require('@/assets/instagram/malka-l0m2p_k5VJ8-unsplash.jpg'),
          },
          {
            id: 5,
            src: require('@/assets/instagram/max-delsid-8-Aght_oHog-unsplash.jpg'),
          },
          {
            id: 6,
            src: require('@/assets/instagram/ricardo-gomez-angel-SAJD-Q4FntE-unsplash.jpg'),
          },
        ],
        tweets: [
          {
            id: 1,
            author: '@vuetifyjs',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rhoncus sit amet nisl sollicitudin auctor. Nam dapibus odio neque, sed proin.',
          },
          {
            id: 2,
            author: '@vuetifyjs',
            date: new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam rhoncus sit amet nisl sollicitudin auctor. Nam dapibus odio neque, sed proin.',
          },
        ],
        tags: [
          'Portfolio',
          'Theme',
          'Camping',
          'Forest',
          'Hiking',
        ],
        relatedPosts: [
          {
            id: 1,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/everett-mcintire-BPCsppbNRMI-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
          {
            id: 2,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/adrian-TvN54bnuQg8-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
          {
            id: 3,
            title: 'Title',
            author: 'John Smith',
            src: require('@/assets/projects/robson-hatsukami-morgan-RTKaEcGKarQ-unsplash.jpg'),
            description: 'Duis fringilla mauris ac pellentesque suscipit. Vestibulum in feugiat felis. Cras eget mattis lectus, sit amet ultricies leo. Donec imperdiet diam eu lectus scelerisque accumsan. Quisque sollicitudin, diam non eleifend tempor, tortor tortor pulvinar enim, sit amet maximus neque metus ac nulla. Morbi pellentesque leo ut nulla scelerisque pulvinar. In hac habitasse platea dictumst.',
            date: new Date().toLocaleDateString(),
            commentCount: 10,
          },
        ],
      }
    },
  },
}
